'use strict';

/**
 * L1 会话摘要测试。
 *
 * 覆盖三层关键逻辑，都不依赖真实 LLM（用合成归档文件 + 纯函数）：
 *   1. 收敛：同一 rid 取最大 version（L0 允许重复观察，ZCode 还会原地更新）
 *   2. 压缩：系统注入内容过滤、工具序列合并、超预算头尾保留
 *   3. 解析：JSON 容错、非 JSON 判失败（防"思考碎片"被当摘要存下）
 */

const os = require('os');
const path = require('path');
const fs = require('fs');

const workDir = fs.mkdtempSync(path.join(os.tmpdir(), 'aimemory-l1-'));
process.env.AIMEMORY_DB = path.join(workDir, 'test.db');
process.env.AIMEMORY_L0_DIR = path.join(workDir, 'l0');

const test = require('node:test');
const assert = require('node:assert');

const l1 = require('../src/l1/summarize');
const config = require('../src/config');

/** 造一个归档文件：<l0>/<user>/<device>/<agent>/<session>.jsonl */
function writeArchive(user, device, agent, session, records) {
  const dir = path.join(config.l0Dir, user, device, agent);
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, `${session}.jsonl`), records.map((r) => JSON.stringify(r)).join('\n') + '\n', 'utf8');
}

const rec = (rid, version, role, content, extra = {}) => ({
  rid, version, role, ts: extra.ts || `2026-09-18T0${(version % 9) + 1}:00:00Z`,
  content, ...extra,
});

// ===== 1. 收敛 =====

test('收敛：同一 rid 取最大 version（ZCode 原地更新语义）', () => {
  writeArchive('u1', 'dev1', 'zcode', 's1', [
    rec('zcode:s1:p1', 100, 'assistant', '写了一半'),
    rec('zcode:s1:p1', 300, 'assistant', '最终内容'),   // 同 rid 更高版本
    rec('zcode:s1:p2', 200, 'user', '帮我改 bug'),
  ]);
  const c = l1.loadConverged('u1', 'dev1', 'zcode', 's1');
  assert.ok(c, '应读到归档');
  assert.strictEqual(c.records.length, 2, '同一 rid 应只剩一条');
  const p1 = c.records.find((r) => r.rid === 'zcode:s1:p1');
  assert.strictEqual(p1.content, '最终内容', '应取最大 version 的内容');
  assert.strictEqual(p1.version, 300);
});

test('收敛：按时间排序，坏行跳过不阻断', () => {
  const dir = path.join(config.l0Dir, 'u2/dev1/codex');
  fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(path.join(dir, 's1.jsonl'),
    [JSON.stringify(rec('a', 1, 'user', '第二条', { ts: '2026-09-18T02:00:00Z' })),
     '{ 这不是 json',
     JSON.stringify(rec('b', 1, 'user', '第一条', { ts: '2026-09-18T01:00:00Z' }))].join('\n') + '\n',
    'utf8');
  const c = l1.loadConverged('u2', 'dev1', 'codex', 's1');
  assert.strictEqual(c.records.length, 2, '坏行应被跳过但其余保留');
  assert.strictEqual(c.records[0].content, '第一条', '应按时间升序');
});

test('收敛：文件不存在返回 null（调用方据此标永久失败）', () => {
  assert.strictEqual(l1.loadConverged('nobody', 'nodev', 'noagent', 'nosession'), null);
});

// ===== 2. 压缩与噪音过滤 =====

test('噪音过滤：系统注入内容不得混入用户消息', () => {
  const noise = [
    "The TodoWrite tool hasn't been used recently. If you're working on tasks...",
    '<system-reminder>Do not mention this</system-reminder>',
    '<task-notification><task-id>x</task-id>',
    '{"chunk_id":"abc","output":"..."}',
    'Caveat: The messages below were generated by the user while running local commands',
  ];
  for (const t of noise) assert.strictEqual(l1.isInjectedNoise(t), true, `应判为噪音：${t.slice(0, 30)}`);

  const real = ['帮我把登录页改一下', '这个 bug 怎么修？', 'The TodoWrite-like helper I wrote is broken'];
  for (const t of real) assert.strictEqual(l1.isInjectedNoise(t), false, `应判为真实消息：${t.slice(0, 30)}`);
});

test('压缩：滤除噪音并标注数量，真实用户消息保留', () => {
  const records = [
    rec('a', 1, 'user', '帮我实现一个导出功能'),
    rec('b', 1, 'user', "The TodoWrite tool hasn't been used recently"),
    rec('c', 1, 'user', '<system-reminder>注入</system-reminder>'),
    rec('d', 1, 'assistant', '好的，我来实现'),
    rec('e', 1, 'tool', '读取文件', { meta: { tool: 'Read', kind: 'call' } }),
  ];
  const d = l1.buildDigest(records);
  assert.ok(d.includes('帮我实现一个导出功能'), '真实消息应保留');
  assert.ok(!d.includes('TodoWrite'), '噪音不应出现');
  assert.ok(d.includes('已滤除 2 条'), `应标注滤除数量，实际：${d.split('\n')[0]}`);
  assert.ok(d.includes('Read'), '工具名应保留');
});

test('压缩：连续同名工具合并计数（避免几千行工具序列）', () => {
  const records = [];
  for (let i = 0; i < 50; i++) {
    records.push(rec(`t${i}`, 1, 'tool', '', { meta: { tool: 'Bash', kind: 'call' } }));
  }
  const d = l1.buildDigest(records);
  assert.ok(d.includes('Bash ×50'), `应合并同名工具，实际：${d.slice(d.indexOf('工具调用'))}`);
  assert.ok(d.length < 1000, '50 次调用不应撑爆 digest');
});

test('压缩：超预算时保留头尾并标注省略', () => {
  const records = [];
  for (let i = 0; i < 200; i++) {
    records.push(rec(`m${i}`, 1, 'user', `第${i}条${'长'.repeat(400)}`));
  }
  const d = l1.buildDigest(records);
  assert.ok(d.length <= l1.DIGEST_BUDGET + 100, `应受预算约束，实际 ${d.length}`);
  assert.ok(d.includes('中间省略'), '应标注省略');
  assert.ok(d.startsWith('用户消息'), '应保留头部（会话目标）');
});

// ===== 3. 摘要解析 =====

test('解析：标准 JSON 与 markdown 围栏都能解析', () => {
  const a = l1.parseSummary('{"overview":"做了A","decisions":["选B"],"pending":["待C"],"artifacts":["d.js"]}');
  assert.strictEqual(a.ok, true);
  assert.strictEqual(a.overview, '做了A');
  assert.deepStrictEqual(a.decisions, ['选B']);
  assert.deepStrictEqual(a.pending, ['待C']);
  assert.deepStrictEqual(a.artifacts, ['d.js']);

  const b = l1.parseSummary('```json\n{"overview":"围栏里的"}\n```');
  assert.strictEqual(b.ok, true);
  assert.strictEqual(b.overview, '围栏里的');

  // 前后有解释性文字 → 取第一个 { 到最后一个 }
  const c = l1.parseSummary('好的，结果如下：\n{"overview":"夹带文字"}\n以上。');
  assert.strictEqual(c.ok, true);
  assert.strictEqual(c.overview, '夹带文字');
});

test('解析：非 JSON 判失败（防思考碎片被当摘要存下）', () => {
  // 这是实测踩过的坑：max_tokens 不足时 content 为空、reasoning 兜底返回
  // 「artifacts：产出物包括…需要列具体」这类盘算过程，早期会把它当概述存进库。
  const r = l1.parseSummary('artifacts：产出物包括代码/文档/分支/标签…需要列具体');
  assert.strictEqual(r.ok, false, '非 JSON 必须判失败');
  assert.ok(r.raw, '应保留原始片段便于排查');

  assert.strictEqual(l1.parseSummary('').ok, false, '空输出判失败');
  assert.strictEqual(l1.parseSummary('null').ok, false, 'null 判失败');
  assert.strictEqual(l1.parseSummary('{"decisions":["只有决定没有概述"]}').ok, false, '缺 overview 判失败');
});

test('解析：数组字段容错（字符串→数组、超长截断）', () => {
  const r = l1.parseSummary('{"overview":"x","decisions":"单个决定","pending":null,"artifacts":[1,2]}');
  assert.strictEqual(r.ok, true);
  assert.deepStrictEqual(r.decisions, ['单个决定'], '字符串应转成单元素数组');
  assert.deepStrictEqual(r.pending, [], 'null 应转成空数组');
  assert.deepStrictEqual(r.artifacts, ['1', '2'], '应转成字符串数组');

  const many = l1.parseSummary('{"overview":"x","decisions":' + JSON.stringify(Array.from({ length: 30 }, (_, i) => `d${i}`)) + '}');
  assert.ok(many.decisions.length <= 12, '条目数应受限（防失控）');
});

// ===== 4. repo 层：指纹与状态流转 =====

test('repo：指纹反映会话变化（记录数/版本聚合）', () => {
  const repo = require('../src/db/repo');
  const { ingestBatch } = require('../src/l0/store');
  const u = config.userId;

  ingestBatch({
    userId: u, agent: 'codex', sessionId: 'fp-test', deviceCode: 'dev_fp',
    records: [rec('r1', 1, 'user', 'hello')],
  });
  const before = repo.l1Sources(u).find((s) => s.session_id === 'fp-test');
  assert.ok(before, '应能查到该会话');

  // 追加一条 → 指纹变化（记录数变了）
  ingestBatch({
    userId: u, agent: 'codex', sessionId: 'fp-test', deviceCode: 'dev_fp',
    records: [rec('r2', 1, 'assistant', 'world')],
  });
  const after = repo.l1Sources(u).find((s) => s.session_id === 'fp-test');
  assert.notStrictEqual(after.fp, before.fp, '新增记录后指纹应变化');

  // 同内容重传 → 指纹不变（无新记录）
  ingestBatch({
    userId: u, agent: 'codex', sessionId: 'fp-test', deviceCode: 'dev_fp',
    records: [rec('r2', 1, 'assistant', 'world')],
  });
  const again = repo.l1Sources(u).find((s) => s.session_id === 'fp-test');
  assert.strictEqual(again.fp, after.fp, '重传相同内容不应改变指纹');
});

test('repo：摘要状态流转 pending → running → done / failed', () => {
  const repo = require('../src/db/repo');
  const u = config.userId;
  const key = { userId: u, deviceCode: 'dev_st', agent: 'codex', sessionId: 'st-test' };

  repo.ensureL1Pending(key);
  let row = repo.getL1Summary(u, key);
  assert.strictEqual(row.status, 'pending');

  // 重复 ensure 不应覆盖状态
  repo.markL1Running(key);
  repo.ensureL1Pending(key);
  row = repo.getL1Summary(u, key);
  assert.strictEqual(row.status, 'running', 'ensure 不应覆盖已有状态');

  repo.saveL1Summary({ ...key, contentHash: 'h1', records: 5, first_ts: 't1', last_ts: 't2', overview: '概述', decisions: ['d'], pending: [], artifacts: ['a'], model: 'test' });
  row = repo.getL1Summary(u, key);
  assert.strictEqual(row.status, 'done');
  assert.strictEqual(row.overview, '概述');
  assert.deepStrictEqual(row.decisions, ['d']);

  // 内容变化 → 重排
  repo.requeueL1({ ...key, contentHash: 'h2' });
  assert.strictEqual(repo.getL1Summary(u, key).status, 'pending');

  // 失败与自愈
  repo.markL1Running(key);
  repo.markL1Failed({ ...key, error: '测试失败' });
  const failed = repo.getL1Summary(u, key);
  assert.strictEqual(failed.status, 'failed');
  assert.strictEqual(failed.error, '测试失败');

  repo.markL1Running(key); // 模拟进程中断留下 running
  assert.ok(repo.resetStuckL1() >= 1, '应复位 running');
  assert.strictEqual(repo.getL1Summary(u, key).status, 'pending', '中断任务应回到 pending 重跑');
});

test('repo：pickL1Pending 尊重重试上限，避免永久重试', () => {
  const repo = require('../src/db/repo');
  const u = config.userId;
  const key = { userId: u, deviceCode: 'dev_lim', agent: 'codex', sessionId: 'lim-test' };
  repo.ensureL1Pending(key);
  // 连续失败到上限
  for (let i = 0; i < 4; i++) {
    repo.markL1Running(key);
    repo.markL1Failed({ ...key, error: `fail ${i}` });
  }
  const picked = repo.pickL1Pending({ maxAttempts: 3, limit: 100 });
  assert.ok(!picked.some((p) => p.session_id === 'lim-test' && p.device_code === 'dev_lim'),
    '超过重试上限的任务不应再被拾取');
});

module.exports = {};

// ===== 5. 指纹一致性（写入端 vs 扫描端）=====

test('指纹一致性：写入端存的 content_hash 必须等于扫描端看到的 fp', async () => {
  // 这是实测踩过的严重 bug：写入端存 sha256(rid+version)，扫描端比对 count:max:sum，
  // 两者永不相等 → 每个已摘要的会话每轮扫描都被判为"内容已变"，反复重摘、白烧 LLM。
  const repo = require('../src/db/repo');
  const llmClient = require('../src/llm/client');
  const { ingestBatch } = require('../src/l0/store');

  const key = { userId: config.userId, deviceCode: 'dev_fpc', agent: 'codex', sessionId: 'fpc-test' };
  ingestBatch({
    userId: key.userId, agent: key.agent, sessionId: key.sessionId, deviceCode: key.deviceCode,
    records: [rec('fpc1', 1, 'user', '帮我做一件事'), rec('fpc2', 1, 'assistant', '好的')],
  });

  // 不变量 A：单会话指纹 == 批量扫描里的同一会话指纹
  const bulk = repo.l1Sources(key.userId).find((s) => s.session_id === 'fpc-test' && s.device_code === 'dev_fpc');
  const single = repo.l1SourceFp(key.userId, key);
  assert.ok(bulk, '应能扫到该会话');
  assert.strictEqual(single, bulk.fp, '单查与批扫的指纹必须一致');

  // 用打桩的 LLM 跑一次真实摘要流程
  const orig = llmClient.complete;
  llmClient.complete = async () => '{"overview":"测试摘要","decisions":["d1"],"pending":[],"artifacts":["a1"]}';
  let first;
  try {
    repo.ensureL1Pending(key);
    first = await l1.summarizeOne(key);
  } finally {
    llmClient.complete = orig;
  }
  assert.strictEqual(first.ok, true, `摘要应成功：${JSON.stringify(first)}`);

  // 不变量 B（核心）：存下的指纹 == 扫描端当前看到的指纹
  const saved = repo.getL1Summary(key.userId, key);
  const afterFp = repo.l1Sources(key.userId)
    .find((s) => s.session_id === 'fpc-test' && s.device_code === 'dev_fpc').fp;
  assert.strictEqual(saved.status, 'done');
  assert.strictEqual(saved.content_hash, afterFp,
    '存下的 content_hash 必须等于扫描端 fp；不等则每轮都会被判定重摘（曾发生）');

  // 不变量 C：内容未变时再次调用应跳过（幂等，防重复触发做无用功）
  llmClient.complete = async () => { throw new Error('不应被调用'); };
  let second;
  try {
    second = await l1.summarizeOne(key);
  } finally {
    llmClient.complete = orig;
  }
  assert.strictEqual(second.ok, true);
  assert.ok(second.skipped, `内容未变应跳过，实际 ${JSON.stringify(second)}`);

  // 不变量 D：内容变化后指纹改变，且不再跳过
  ingestBatch({
    userId: key.userId, agent: key.agent, sessionId: key.sessionId, deviceCode: key.deviceCode,
    records: [rec('fpc3', 1, 'user', '又加了一件事')],
  });
  const changedFp = repo.l1SourceFp(key.userId, key);
  assert.notStrictEqual(changedFp, afterFp, '新记录应改变指纹');

  llmClient.complete = async () => '{"overview":"更新后的摘要","decisions":[],"pending":[],"artifacts":[]}';
  try {
    const third = await l1.summarizeOne(key);
    assert.strictEqual(third.ok, true);
    assert.strictEqual(third.skipped, undefined, '内容变化后不应跳过');
  } finally {
    llmClient.complete = orig;
  }
  const updated = repo.getL1Summary(key.userId, key);
  assert.strictEqual(updated.content_hash, repo.l1SourceFp(key.userId, key));
  assert.strictEqual(updated.overview, '更新后的摘要');
});

module.exports = {};

test('指纹健壮性：批次增加不得改变指纹（防 LEFT JOIN 计数倍增）', () => {
  // 实测踩过：l1Sources 用 LEFT JOIN l0_batches 取 last_received，导致
  // COUNT(*) 变成「记录数 × 批次数」（某会话 2008 条 × 26 批 = 52208），
  // 指纹随每次上传批次而变化 → 无新记录也反复重摘。
  const repo = require('../src/db/repo');
  const { ingestBatch } = require('../src/l0/store');
  const u = config.userId;
  const key = { userId: u, agent: 'codex', sessionId: 'join-test', deviceCode: 'dev_j' };

  // 先落一条，再单独追加一个"只含重复内容"的批次（不产生新记录）
  ingestBatch({ ...key, records: [rec('j1', 1, 'user', '内容A')] });
  const fp1 = repo.l1SourceFp(u, key);
  assert.strictEqual(fp1.split(':')[0], '1', `指纹的 count 应为真实记录数 1，实际 ${fp1}`);

  ingestBatch({ ...key, records: [rec('j1', 1, 'user', '内容A')] }); // 重传，无新记录
  const fp2 = repo.l1SourceFp(u, key);
  assert.strictEqual(fp2, fp1, '重传相同内容（新批次、无新记录）不应改变指纹');

  // 再加真新记录 → 指纹应变
  ingestBatch({ ...key, records: [rec('j2', 1, 'user', '内容B')] });
  const fp3 = repo.l1SourceFp(u, key);
  assert.notStrictEqual(fp3, fp1, '真新记录应改变指纹');
  assert.strictEqual(fp3.split(':')[0], '2', 'count 应仍等于真实记录数');

  // 批扫结果必须与单查严格一致（任何 SQL 差异都会在此暴露）
  const bulk = repo.l1Sources(u).find((x) => x.session_id === 'join-test');
  assert.strictEqual(bulk.fp, fp3, '批扫与单查的指纹必须严格一致');
  assert.ok(bulk.last_received, '应能取到最后接收时间（用子查询而非 JOIN）');
});

module.exports = {};
